-- supabase/seed.sql
--
-- Intentionally empty.
--
-- Reference data used to live here, but `supabase db push` applies migrations
-- and never runs this file, so a rebuilt project came up with empty role,
-- department, status_code and package tables -- and the migrations that
-- resolve those rows by code or name (20260513, 20260514) failed or silently
-- mapped nothing. The rows now live in migrations, which run everywhere this
-- file does and in the one place it doesn't:
--
--   20260312000001_seed_reference_data.sql   role, department, status_code, package
--   20260330_seed_package_department.sql     package_department
--   20260513_seed_test_catalog.sql           test_catalog
--   20260514_seed_package_test.sql           package_test
--
-- Probe accounts and the probe company come from `npm run probe:bootstrap`.
--
-- Note for later: scripts/supabase/seed-reference-data.mjs still carries its
-- own third copy of role/department/status_code. It is guarded and harmless,
-- but it is a second place for these rows to drift and should be pointed at
-- the migrations above.
