-- supabase/migrations/20260312000000_core_schema_baseline.sql
--
-- Baseline: the 12 core tables that were created directly in the Supabase
-- dashboard and never captured as a migration. Without this file,
-- `supabase db reset` fails outright -- every later migration in this
-- directory assumes these tables already exist.
--
-- Source: memory-bank/database/schema.txt (committed 2026-03-21, before the
-- earliest existing migration 20260313), reordered here by foreign-key
-- dependency so the file applies top-to-bottom on an empty database.
-- Table bodies are otherwise verbatim -- no columns added, removed, or edited.
--
-- Deliberately NOT in this file: row-level security. RLS is enabled and
-- policies are defined by 20260320_baseline_core_rls.sql and its successors,
-- which replay on top of this.
--
-- Prefix is dated 20260312 so it sorts ahead of every existing migration.

create table public.role (
  roleid bigint generated by default as identity not null,
  rolename character varying(50) not null,
  roledescription character varying(255) null,
  issystemrole boolean null default true,
  isactive boolean null default true,
  constraint role_pkey primary key (roleid),
  constraint role_rolename_key unique (rolename)
) TABLESPACE pg_default;

create table public.department (
  departmentid bigint generated by default as identity not null,
  code character varying(20) not null,
  name character varying(100) not null,
  isactive boolean null default true,
  constraint department_pkey primary key (departmentid),
  constraint department_code_key unique (code)
) TABLESPACE pg_default;

create table public.status_code (
  statuscodeid bigint generated by default as identity not null,
  domain character varying(30) not null,
  code character varying(30) not null,
  label character varying(50) not null,
  description character varying(255) null,
  isterminal boolean null default false,
  isactive boolean null default true,
  sortorder integer null,
  constraint status_code_pkey primary key (statuscodeid)
) TABLESPACE pg_default;

create table public.package (
  packageid bigint generated by default as identity not null,
  packagename character varying(100) not null,
  category character varying(50) null,
  description character varying(255) null,
  isactive boolean null default true,
  constraint package_pkey primary key (packageid),
  constraint package_packagename_key unique (packagename)
) TABLESPACE pg_default;

create table public.company (
  companyid bigint generated by default as identity not null,
  name character varying(150) not null,
  address character varying(255) null,
  contactperson character varying(100) null,
  contactnumber character varying(30) null,
  emailaddress character varying(100) null,
  isactive boolean null default true,
  constraint company_pkey primary key (companyid)
) TABLESPACE pg_default;

create table public.patient (
  patientid uuid not null default extensions.uuid_generate_v4 (),
  fullname character varying(100) not null,
  dateofbirth date not null,
  sex character varying(10) not null,
  nationality character varying(50) null,
  contactnumber character varying(30) null,
  emailaddress character varying(100) null,
  governmentid character varying(50) null,
  createdat timestamp with time zone not null default now(),
  updatedat timestamp with time zone null,
  constraint patient_pkey primary key (patientid),
  constraint patient_governmentid_key unique (governmentid)
) TABLESPACE pg_default;

create table public.user_account (
  userid uuid not null,
  roleid bigint not null,
  companyid bigint null,
  patientid uuid null,
  username character varying(100) not null,
  isactive boolean null default true,
  islocked boolean null default false,
  lastloginat timestamp with time zone null,
  createdat timestamp with time zone not null default now(),
  constraint user_account_pkey primary key (userid),
  constraint user_account_username_key unique (username),
  constraint user_account_companyid_fkey foreign KEY (companyid) references company (companyid),
  constraint user_account_patientid_fkey foreign KEY (patientid) references patient (patientid),
  constraint user_account_roleid_fkey foreign KEY (roleid) references role (roleid),
  constraint user_account_userid_fkey foreign KEY (userid) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.audit_log (
  auditid bigint generated by default as identity not null,
  userid uuid null,
  timestamp timestamp with time zone not null default now(),
  actiontype character varying(50) not null,
  entityname character varying(50) null,
  entityid character varying(50) null,
  details text null,
  ipaddress character varying(45) null,
  constraint audit_log_pkey primary key (auditid),
  constraint audit_log_userid_fkey foreign KEY (userid) references user_account (userid)
) TABLESPACE pg_default;

create table public.peme_case (
  caseid uuid not null default extensions.uuid_generate_v4 (),
  casenumber character varying(30) not null,
  patientid uuid not null,
  companyid bigint null,
  packageid bigint not null,
  casecategory character varying(20) null,
  isrush boolean null default false,
  casestatuscodeid bigint not null,
  registrationtimestamp timestamp with time zone not null default now(),
  triagecompletedtimestamp timestamp with time zone null,
  releasedtimestamp timestamp with time zone null,
  archivetimestamp timestamp with time zone null,
  portalvisible boolean null default false,
  remarks character varying(255) null,
  waiversigned boolean null default false,
  constraint peme_case_pkey primary key (caseid),
  constraint peme_case_casenumber_key unique (casenumber),
  constraint peme_case_casestatuscodeid_fkey foreign KEY (casestatuscodeid) references status_code (statuscodeid),
  constraint peme_case_companyid_fkey foreign KEY (companyid) references company (companyid),
  constraint peme_case_packageid_fkey foreign KEY (packageid) references package (packageid),
  constraint peme_case_patientid_fkey foreign KEY (patientid) references patient (patientid)
) TABLESPACE pg_default;

create table public.department_visit (
  visitid bigint generated by default as identity not null,
  caseid uuid not null,
  departmentid bigint not null,
  visitstatuscodeid bigint not null,
  queuenumber character varying(20) null,
  timepending timestamp with time zone null,
  timestarted timestamp with time zone null,
  timecompleted timestamp with time zone null,
  remarks character varying(255) null,
  constraint department_visit_pkey primary key (visitid),
  constraint department_visit_caseid_fkey foreign KEY (caseid) references peme_case (caseid),
  constraint department_visit_departmentid_fkey foreign KEY (departmentid) references department (departmentid),
  constraint department_visit_visitstatuscodeid_fkey foreign KEY (visitstatuscodeid) references status_code (statuscodeid)
) TABLESPACE pg_default;

create table public.peme_decision (
  decisionid bigint generated by default as identity not null,
  caseid uuid not null,
  physicianuserid uuid not null,
  fitnessstatus character varying(20) not null,
  decisiondate timestamp with time zone not null default now(),
  remarks character varying(255) null,
  constraint peme_decision_pkey primary key (decisionid),
  constraint peme_decision_caseid_key unique (caseid),
  constraint peme_decision_caseid_fkey foreign KEY (caseid) references peme_case (caseid),
  constraint peme_decision_physicianuserid_fkey foreign KEY (physicianuserid) references user_account (userid)
) TABLESPACE pg_default;

create table public.result_item (
  resultid bigint generated by default as identity not null,
  visitid bigint not null,
  caseid uuid not null,
  departmentid bigint not null,
  testname character varying(100) not null,
  value character varying(100) null,
  unit character varying(20) null,
  referencerange character varying(50) null,
  isabnormal boolean null default false,
  verificationstatus character varying(20) null,
  verifiedbyuserid uuid null,
  verifiedat timestamp with time zone null,
  remarks character varying(255) null,
  constraint result_item_pkey primary key (resultid),
  constraint result_item_caseid_fkey foreign KEY (caseid) references peme_case (caseid),
  constraint result_item_departmentid_fkey foreign KEY (departmentid) references department (departmentid),
  constraint result_item_verifiedbyuserid_fkey foreign KEY (verifiedbyuserid) references user_account (userid),
  constraint result_item_visitid_fkey foreign KEY (visitid) references department_visit (visitid)
) TABLESPACE pg_default;

